name: ci-build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.8]
        pytorch-version: [0.4.1, 1.5.0]
        exclude:
          - python-version: 3.8
            pytorch-version: 0.4.1
        include:
          - python-version: 3.7
            pytorch-version: 0.4.1

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Caching dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ matrix.python-version }}-pytorch-${{ matrix.pytorch-version }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-py-${{ matrix.python-version }}-pytorch-${{ matrix.pytorch-version }}-pip-

      - name: Install dependencies with PyTorch ${{ matrix.pytorch-version }}
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install torch==${{ matrix.pytorch-version }} -f https://download.pytorch.org/whl/torch_stable.html
          pip install -e .[tests]

      - name: Run tests and generate coverage
        run: |
          pytest --cov=mymod --cov-report=xml tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-ci
          fail_ci_if_error: false
